name             'runtime'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures runtime'
long_description 'Installs/Configures runtime'
version          '0.1.0'

depends 'docker'
depends 'runit'
