name             'provisioner'
maintainer       'Greg Osuri'
maintainer_email 'gosuri@gmail.com'
license          'MIT'
description      'Installs/Configures provisioner'
long_description 'Installs/Configures provisioner'
version          '0.1.0'

depends 'docker'
depends 'runit'
